# Generated by Django 4.0.5 on 2022-06-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date', models.BigIntegerField(blank=True, null=True)),
                ('patient_id', models.BigIntegerField(blank=True, null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'notification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('can_be_pregnant', models.BooleanField(blank=True, null=True)),
                ('checkinterval', models.FloatField(blank=True, null=True)),
                ('date_of_birthday', models.BigIntegerField(blank=True, null=True)),
                ('date_operation', models.BigIntegerField(blank=True, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('is_pregnant', models.BooleanField(blank=True, null=True)),
                ('lowthslev', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('operation', models.CharField(blank=True, max_length=255, null=True)),
                ('pathology_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pretreatment', models.FloatField(blank=True, null=True)),
                ('pretreatment_drug', models.CharField(blank=True, max_length=255, null=True)),
                ('ths_date', models.BigIntegerField(blank=True, null=True)),
                ('ths_result', models.FloatField(blank=True, null=True)),
                ('treatment', models.FloatField(blank=True, null=True)),
                ('treatment_drug', models.CharField(blank=True, max_length=255, null=True)),
                ('upthslev', models.FloatField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'patient',
                'managed': False,
            },
        ),
    ]
