FROM python:3

ENV PYTHONUNBUFFERED=1
ENV HYPOTHYRO_DATABASE_NAME=""
ENV HYPOTHYRO_DATABASE_USER=""
ENV HYPOTHYRO_DATABASE_PASSWORD=""
ENV HYPOTHYRO_DATABASE_HOST=""

RUN mkdir /code
WORKDIR /code
ADD requirements.txt /code/
RUN pip install -r requirements.txt
ADD . /code/
